apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: chatbot-release-010x-test 
  janus-idp.io/tekton: chatbot-release-010x-test
  backstage.io/kubernetes-id: chatbot-release-010x-test
  backstage.io/kubernetes-namespace: rhdh-app 
  app.kubernetes.io/part-of: chatbot-release-010x-test
resources: 
- application-dev.yaml