apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: chatbot-release-010x-test
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: chatbot-release-010x-test 
  name: chatbot-release-010x-test
spec:
  ports:
  - port: 8501
    protocol: TCP
    targetPort: 8501
  selector:
    app.kubernetes.io/instance: chatbot-release-010x-test 
