apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: chatbot-release-010x-test
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jdubrick-ai/chatbot-release-010x-test:a857b897efba973ad8151efc8d8e84e26c6b187c@sha256:895a3fc3e3dba8a85d712a109f3c420d460a1f9995b06ce884da6a347dc8f82f # use pre-built to bootstrap 
          name: app-inference
